// Code generated by goyacc -o y.go parser.y. DO NOT EDIT.

//line parser.y:2
package parser

import __yyfmt__ "fmt"

//line parser.y:2

import "fmt"

//line parser.y:8
type yySymType struct {
	yys int
	val any
}

const String = 57346
const Number = 57347
const Print = 57348
const Label = 57349
const Type = 57350
const Get = 57351
const Put = 57352
const Post = 57353
const Delete = 57354
const Head = 57355
const Header = 57356
const Body = 57357
const Json = 57358
const JsonStr = 57359
const Comment = 57360
const Bool = 57361
const Write = 57362
const Append = 57363
const StringFunc = 57364
const CodeBlock = 57365
const If = 57366
const For = 57367
const Read = 57368
const Map = 57369
const Len = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"String",
	"Number",
	"Print",
	"Label",
	"Type",
	"Get",
	"Put",
	"Post",
	"Delete",
	"Head",
	"Header",
	"Body",
	"Json",
	"JsonStr",
	"Comment",
	"Bool",
	"Write",
	"Append",
	"StringFunc",
	"CodeBlock",
	"If",
	"For",
	"Read",
	"Map",
	"Len",
	"'='",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'('",
	"')'",
	"','",
	"'.'",
	"'['",
	"']'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 7,
	30, 58,
	31, 58,
	32, 58,
	33, 58,
	-2, 18,
	-1, 8,
	30, 61,
	31, 61,
	32, 61,
	33, 61,
	-2, 12,
	-1, 12,
	30, 59,
	31, 59,
	32, 59,
	33, 59,
	-2, 10,
	-1, 15,
	30, 63,
	31, 63,
	32, 63,
	33, 63,
	-2, 14,
	-1, 19,
	30, 57,
	31, 57,
	32, 57,
	33, 57,
	-2, 19,
	-1, 20,
	30, 56,
	31, 56,
	32, 56,
	33, 56,
	-2, 20,
	-1, 21,
	30, 60,
	31, 60,
	32, 60,
	33, 60,
	-2, 21,
}

const yyPrivate = 57344

const yyLast = 254

var yyAct = [...]uint8{
	72, 79, 8, 8, 105, 73, 6, 171, 146, 170,
	35, 13, 77, 12, 12, 89, 19, 20, 104, 92,
	83, 25, 26, 27, 28, 29, 185, 45, 45, 82,
	184, 21, 43, 24, 38, 62, 65, 43, 31, 39,
	40, 182, 181, 45, 43, 85, 90, 93, 94, 191,
	87, 84, 96, 91, 71, 159, 88, 98, 95, 97,
	163, 190, 45, 113, 111, 120, 118, 126, 162, 129,
	43, 132, 107, 108, 109, 110, 70, 161, 86, 45,
	125, 45, 100, 101, 102, 103, 160, 139, 43, 45,
	138, 123, 43, 121, 43, 44, 42, 158, 157, 155,
	154, 153, 127, 45, 43, 45, 189, 43, 188, 145,
	187, 186, 145, 145, 145, 145, 149, 150, 151, 152,
	183, 180, 156, 19, 20, 22, 7, 23, 25, 26,
	27, 28, 29, 144, 143, 166, 169, 5, 21, 30,
	32, 38, 142, 33, 34, 31, 39, 40, 173, 75,
	74, 141, 76, 140, 25, 26, 27, 28, 29, 137,
	130, 81, 82, 37, 78, 75, 74, 38, 76, 50,
	51, 31, 39, 40, 48, 49, 50, 51, 124, 106,
	78, 134, 133, 38, 69, 68, 67, 31, 39, 40,
	59, 58, 57, 47, 46, 63, 122, 64, 66, 114,
	115, 60, 119, 172, 114, 115, 167, 112, 131, 168,
	106, 147, 82, 61, 116, 81, 128, 82, 40, 116,
	164, 99, 136, 165, 135, 179, 178, 177, 176, 175,
	174, 148, 117, 56, 55, 54, 53, 52, 80, 15,
	15, 2, 36, 41, 18, 17, 16, 14, 11, 10,
	9, 4, 3, 1,
}

var yyPact = [...]int16{
	119, 119, -1000, -1000, -1000, -1000, -1000, 67, 66, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, 160, 159, 144, 233, 232, 231, 230, 229,
	158, 157, 156, 194, 190, -1000, -1000, -1000, 152, 151,
	150, -1000, 145, 13, 145, 8, 12, 214, 161, 161,
	161, 161, 165, 165, 165, 165, 165, 200, 228, 195,
	70, 173, 68, 155, 57, 44, 79, 209, 125, 201,
	144, -1000, -1000, -1000, -1000, -1000, 0, -1000, -1000, -10,
	-1000, 148, 147, -1000, 219, -1000, 144, -1000, -1000, -1000,
	217, 124, 55, -1000, 52, 118, 116, 107, 99, 98,
	137, 137, -1000, -1000, 196, -1000, 227, 196, 196, 196,
	196, 65, 64, 63, -1000, -1000, -1000, 87, 62, 61,
	19, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 51, 42,
	-1000, 33, 25, 216, 202, -30, -32, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 199, -1000, -1000,
	-1000, -1000, -1000, 226, 225, 224, -1000, 223, 222, 221,
	-1000, -1000, -1000, -1000, 86, 7, 6, 85, -5, -9,
	-1000, -1000, -1000, -1000, 76, 75, 73, 71, 26, 14,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000,
}

var yyPgo = [...]uint8{
	0, 253, 241, 252, 251, 6, 250, 249, 248, 12,
	11, 1, 247, 238, 246, 245, 244, 5, 10, 0,
	33, 242, 163, 4, 18, 8,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 2, 2, 4, 4, 4,
	4, 4, 4, 4, 4, 4, 4, 4, 7, 5,
	5, 5, 6, 6, 6, 6, 6, 6, 6, 6,
	12, 12, 12, 14, 14, 14, 13, 8, 19, 19,
	19, 17, 17, 17, 3, 3, 3, 3, 3, 3,
	3, 3, 9, 9, 9, 9, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 23, 24, 24, 24,
	25, 25, 25, 10, 10, 10, 10, 10, 11, 11,
	11, 11, 18, 18, 15, 15, 15, 16, 16, 16,
	16, 21, 22, 22,
}

var yyR2 = [...]int8{
	0, 1, 2, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 4, 3, 4, 4, 4, 4, 4,
	6, 6, 6, 6, 6, 6, 4, 4, 4, 4,
	4, 4, 4, 4, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 2, 1, 2, 0,
	2, 2, 0, 4, 4, 4, 4, 4, 3, 3,
	5, 5, 4, 4, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 4,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, -4, 18, -5, 7, -11, -6,
	-7, -8, -9, -10, -12, -13, -14, -15, -16, 4,
	5, 19, 6, 8, -20, 9, 10, 11, 12, 13,
	20, 26, 21, 24, 25, -18, -21, -22, 22, 27,
	28, -2, 29, 37, 29, 37, 34, 34, 30, 31,
	32, 33, 4, 4, 4, 4, 4, 34, 34, 34,
	7, 19, -11, 5, 7, -11, -22, 34, 34, 34,
	-20, -10, -19, -17, 5, 4, 7, -9, 19, -11,
	-13, 16, 17, 7, 38, -19, -20, -17, -10, 7,
	38, -5, 7, 35, -11, -10, -17, -9, -18, 7,
	-20, -20, -20, -20, -24, -23, 14, -24, -24, -24,
	-24, -5, 7, -17, 4, 5, 19, 4, -5, 7,
	-17, 23, 23, 23, 23, 23, 23, 23, 7, -11,
	35, 7, -11, 34, 34, 5, 5, 35, 35, 35,
	35, 35, 35, 35, 35, -23, -25, 15, 4, -25,
	-25, -25, -25, 36, 36, 36, 35, 36, 36, 36,
	35, 35, 35, 35, 4, 7, -11, 4, 7, -11,
	39, 39, 4, -19, 4, 4, 4, 4, 4, 4,
	35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
	35, 35,
}

var yyDef = [...]int8{
	0, -2, 1, 3, 4, 5, 6, -2, -2, 7,
	8, 9, -2, 11, 13, -2, 15, 16, 17, -2,
	-2, -2, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 62, 64, 65, 0, 0,
	0, 2, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 69, 69, 69, 69, 69, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	44, 45, 46, 47, 56, 57, 58, 59, 60, 61,
	63, 0, 0, 78, 0, 48, 49, 50, 51, 79,
	0, 0, 58, 24, 61, 0, 0, 59, 62, 0,
	52, 53, 54, 55, 72, 67, 0, 72, 72, 72,
	72, 0, 0, 0, 19, 20, 21, 0, 0, 0,
	0, 84, 85, 86, 87, 88, 89, 90, 0, 0,
	91, 0, 0, 0, 0, 0, 0, 22, 23, 25,
	26, 27, 28, 29, 37, 68, 73, 0, 66, 74,
	75, 76, 77, 0, 0, 0, 36, 0, 0, 0,
	82, 83, 92, 93, 0, 0, 0, 0, 0, 0,
	80, 81, 70, 71, 0, 0, 0, 0, 0, 0,
	38, 39, 40, 41, 42, 43, 30, 31, 32, 33,
	34, 35,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	34, 35, 32, 30, 36, 31, 37, 33, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 29, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 38, 3, 39,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:66
		{
			PrintYySymDebug(yyDollar[1])
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:72
		{
			PrintYySym(yyDollar[3])
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:73
		{
			PrintGlobalYySym(yyDollar[3])
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:74
		{
			println("")
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:75
		{
			PrintYySym(yySymType{val: WalkField(yyDollar[3].val.(string))})
		}
	case 26:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:76
		{
			PrintYySym(yyDollar[3])
		}
	case 27:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:77
		{
			PrintYySym(yyDollar[3])
		}
	case 28:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:78
		{
			PrintYySym(yyDollar[3])
		}
	case 29:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:79
		{
			PrintYySym(yyDollar[3])
		}
	case 30:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:82
		{
			WriteFile(yyDollar[3].val, yyDollar[5].val.(string))
		}
	case 31:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:83
		{
			WriteFile(GlobalVarRead(yyDollar[3]), yyDollar[5].val.(string))
		}
	case 32:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:84
		{
			WriteFile(yyDollar[3].val, yyDollar[5].val.(string))
		}
	case 33:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:87
		{
			AppendFile(yyDollar[3].val, yyDollar[5].val.(string))
		}
	case 34:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:88
		{
			AppendFile(GlobalVarRead(yyDollar[3]), yyDollar[5].val.(string))
		}
	case 35:
		yyDollar = yyS[yypt-6 : yypt+1]
//line parser.y:89
		{
			AppendFile(yyDollar[3].val, yyDollar[5].val.(string))
		}
	case 36:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:92
		{
			yyVAL = yySymType{val: ReadFile(yyDollar[3].val.(string))}
		}
	case 37:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:95
		{
			PrintType(yyDollar[3])
		}
	case 38:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:98
		{
			yyVAL = yySymType{val: StrToMap(yyDollar[3].val)}
		}
	case 39:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:99
		{
			yyVAL = yySymType{val: StrToMap(GlobalVarRead(yyDollar[3]))}
		}
	case 40:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:100
		{
			yyVAL = yySymType{val: StrToMap(WalkField(yyDollar[3].val.(string)))}
		}
	case 41:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:103
		{
			yyVAL = yySymType{val: ToJsonStr(yyDollar[3].val)}
		}
	case 42:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:104
		{
			yyVAL = yySymType{val: ToJsonStr(GlobalVarRead(yyDollar[3]))}
		}
	case 43:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:105
		{
			yyVAL = yySymType{val: ToJsonStr(WalkField(yyDollar[3].val.(string)))}
		}
	case 44:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:108
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 45:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:109
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 46:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:110
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 47:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:111
		{
			GlobalVarWrite(yyDollar[1], yyDollar[3].val)
		}
	case 48:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:112
		{
			GlobalVarFieldWrite(yyDollar[1].val.(string), yyDollar[3].val)
		}
	case 49:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:113
		{
			GlobalVarFieldWrite(yyDollar[1].val.(string), yyDollar[3].val)
		}
	case 50:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:114
		{
			GlobalVarFieldWrite(yyDollar[1].val.(string), yyDollar[3].val)
		}
	case 51:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:115
		{
			GlobalVarFieldWrite(yyDollar[1].val.(string), yyDollar[3].val)
		}
	case 52:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:118
		{
			yyVAL = yySymType{val: ValAdd(yyDollar[1].val, yyDollar[3].val)}
		}
	case 53:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:119
		{
			yyVAL = yySymType{val: ValMinus(yyDollar[1].val, yyDollar[3].val)}
		}
	case 54:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:120
		{
			yyVAL = yySymType{val: ValMul(yyDollar[1].val, yyDollar[3].val)}
		}
	case 55:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:121
		{
			yyVAL = yySymType{val: ValDiv(yyDollar[1].val, yyDollar[3].val)}
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:124
		{
			yyVAL = yyDollar[1]
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:125
		{
			yyVAL = yyDollar[1]
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:126
		{
			yyVAL = yySymType{val: GlobalVarRead(yyDollar[1])}
		}
	case 59:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:127
		{
			yyVAL = yyDollar[1]
		}
	case 60:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:128
		{
			yyVAL = yyDollar[1]
		}
	case 61:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:129
		{
			yyVAL = yySymType{val: WalkField(yyDollar[1].val.(string))}
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:130
		{
			yyVAL = yyDollar[1]
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:131
		{
			yyVAL = yyDollar[1]
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:132
		{
			yyVAL = yyDollar[1]
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:133
		{
			yyVAL = yyDollar[1]
		}
	case 66:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:136
		{
			yyVAL = yyDollar[2]
		}
	case 67:
		yyDollar = yyS[yypt-1 : yypt+1]
//line parser.y:139
		{
			yyVAL = yyDollar[1]
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:140
		{
			yyVAL = joinHeaders(yyDollar[1], yyDollar[2])
		}
	case 69:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:141
		{
			yyVAL = yySymType{val: nil}
		}
	case 70:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:144
		{
			yyVAL = yySymType{val: yyDollar[2].val}
		}
	case 71:
		yyDollar = yyS[yypt-2 : yypt+1]
//line parser.y:145
		{
			yyVAL = yySymType{val: yyDollar[2].val}
		}
	case 72:
		yyDollar = yyS[yypt-0 : yypt+1]
//line parser.y:146
		{
			yyVAL = yySymType{val: nil}
		}
	case 73:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:149
		{
			yyVAL = HttpSend("GET", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 74:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:150
		{
			yyVAL = HttpSend("PUT", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 75:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:151
		{
			yyVAL = HttpSend("POST", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 76:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:152
		{
			yyVAL = HttpSend("DELETE", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 77:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:153
		{
			yyVAL = HttpSend("HEAD", yyDollar[2].val.(string), yyDollar[3], yyDollar[4])
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:157
		{
			yyVAL = yySymType{val: yyDollar[1].val.(string) + "." + yyDollar[3].val.(string)}
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:160
		{
			yyVAL = yySymType{val: yyDollar[1].val.(string) + "." + yyDollar[3].val.(string)}
		}
	case 80:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:163
		{
			yyVAL = yySymType{val: fmt.Sprintf("%s.[%d]", yyDollar[1].val, yyDollar[4].val)}
		}
	case 81:
		yyDollar = yyS[yypt-5 : yypt+1]
//line parser.y:166
		{
			yyVAL = yySymType{val: fmt.Sprintf("%s.[%d]", yyDollar[1].val, yyDollar[4].val)}
		}
	case 82:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:171
		{
			yyVAL = yySymType{val: ToStr(GlobalVarRead(yyDollar[3]))}
		}
	case 83:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:172
		{
			yyVAL = yySymType{val: ToStr(WalkField(yyDollar[3].val.(string)))}
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:175
		{
			RunIfCond(GlobalVarRead(yyDollar[2]), yyDollar[3].val)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:176
		{
			RunIfCond(yyDollar[2].val, yyDollar[3].val)
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:177
		{
			RunIfCond(WalkField(yyDollar[2].val.(string)), yyDollar[3].val)
		}
	case 87:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:180
		{
			RepeatBlock(yyDollar[2].val, yyDollar[3].val)
		}
	case 88:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:181
		{
			RepeatBlock(GlobalVarRead(yyDollar[2]), yyDollar[3].val)
		}
	case 89:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:182
		{
			RepeatBlock(WalkField(yyDollar[2].val.(string)), yyDollar[3].val)
		}
	case 90:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:183
		{
			RepeatBlock(yyDollar[2].val, yyDollar[3].val)
		}
	case 91:
		yyDollar = yyS[yypt-3 : yypt+1]
//line parser.y:186
		{
			yyVAL = yySymType{val: map[string]any{}}
		}
	case 92:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:189
		{
			yyVAL = yySymType{val: CalcLen(GlobalVarRead(yyDollar[3]))}
		}
	case 93:
		yyDollar = yyS[yypt-4 : yypt+1]
//line parser.y:190
		{
			yyVAL = yySymType{val: CalcLen(WalkField(yyDollar[3].val.(string)))}
		}
	}
	goto yystack /* stack new state and value */
}
